config/routes.rb
Rails.application.routes.draw do
  resources :post_subs
  resources :posts, except: [:index] do
    member do
      post 'upvote'
      post 'downvote'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :subs, except: [:destroy]
  resources :comments, only: [:create, :show] do
    member do
      post 'upvote'
      post 'downvote'
    end
  end
  # resources :comments, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :body, presence: true    
    validates :post_id, presence: true    
    validates :author_id, presence: true

    has_many :comments, foreign_key: "parent_comment_id", class_name: "Comment"
    has_many :votes, as: :votable
    
    belongs_to :author, foreign_key: "author_id", class_name: "User"
    belongs_to :post

    def total
        self.votes.sum(:value)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.build(comment_params)

        if @comment.save!
            flash.now[:notice] = 'Comment created'
            redirect_to post_path(@comment.post_id)
        else
            flash.now[:error] = @comment.errors.full_messages
            redirect_to post_path(params[:post_id])
        end
    end

    def show
        @comment = Comment.find(params[:id])
    end

    def upvote
        vote(1)
    end

    def downvote
        vote(-1)
    end

    private

    def comment_params
        params.permit(:body, :post_id, :author_id, :parent_comment_id)
    end

    def vote(direction)
        @comment = Comment.find(params[:id])
        @user_vote = @comment.votes.find_or_initialize_by(user_id: current_user.id)

        @user_vote.update(value: direction)

        redirect_back(fallback_location: subs_path)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<ul>
    <li>
        Comment: <%= comment.body %>
    </li>
    <li>
        By: <%= comment.author.email %>
    </li>
    <li>
        Created at: <%= comment.created_at %>
    </li>

    <button type="button" class="btn btn-success"><%= button_to 'Upvote', upvote_comment_path(comment), class: 'btn' %></button>
    <button type="button" class="btn btn-danger"><%= button_to 'Downvote', downvote_comment_path(comment), class: 'btn' %></button>
    
    <%= comment.votes.sum(:value) %>

<%= link_to "View comment", comment_path(comment.id) %>

<%= render partial: "comments/comment", collection: comment.comments %>

</ul>

app/views/comments/_form.html.erb
<%= form_with url: comments_path do |form| %>
    <%= form.hidden_field :author_id, value: current_user.id %>
    <%= form.hidden_field :post_id, value: params[:id] %>
    <%= form.text_field :body %>
    <%= form.submit %>
<% end %>

app/views/comments/show.html.erb
<%= @comment.body %>

<%= form_with url: comments_path do |form| %>
    <%= form.hidden_field :post_id, value: @comment.post.id %>
    <%= form.hidden_field :author_id, value: current_user.id %>
    <%= form.hidden_field :parent_comment_id, value: params[:id] %>
    <%= form.text_field :body %>
    <%= form.submit %>
 <% end %>