config/routes.rb
Rails.application.routes.draw do
  resources :post_subs
  resources :posts, except: [:index] do
    member do
      post 'upvote'
      post 'downvote'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :subs, except: [:destroy]
  resources :comments, only: [:create, :show] do
    member do
      post 'upvote'
      post 'downvote'
    end
  end
  # resources :comments, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
end

app/models/sub.rb
class Sub < ApplicationRecord
    belongs_to :moderator, foreign_key: "moderator_id", primary_key: "id", class_name: 'User'

    has_many :post_subs, dependent: :destroy, inverse_of: :sub
    has_many :posts, through: :post_subs, source: :post

    def sorted_posts
        self.posts.sort_by(&:total).reverse
    end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :check_for_moderator, only: [:edit]

    def new
        @sub = current_user.subs.new
    end

    def create
        @sub = current_user.subs.new(sub_params)
        if @sub.save
            flash.now[:notice] = "Sub was successfully created"
            redirect_to @sub
        else
            flash.now[:error] = @sub.errors.full_messages
            render 'new'
        end
    end

    def index
        @subs = Sub.all
    end

    def show
        @sub = Sub.find(params[:id])
        @posts = @sub.sorted_posts
        @votes = Vote.where(votable_type: "Post")
    end

    def edit
        @sub = Sub.find(params[:id])
    end

    def update
        @sub = Sub.find(params[:id])
        if @sub.update(sub_params)
            flash.now[:notice] = "Sub was successfully updated"
            redirect_to @sub
        else
            flash.now[:error] = @sub.errors.full_messages
            render 'edit'
        end
    end

    def check_for_moderator
        current_user && Sub.find(params[:id]).moderator_id == current_user.id
    end

    def sub_params
        params.require(:sub).permit(:title, :description)
    end


end

app/helpers/sub_helper.rb
module SubHelper
end

app/views/subs/_form.html.erb
<% @sub.persisted? ? method = "update" : method = "new" %>

<%= form_for @sub do |form| %>
    <%= form.text_field :title %>
    <%= form.text_area :description, size: "60x10" %>
    <%= form.submit %>
<% end %>

app/views/subs/edit.html.erb
<%= render "form" %>

app/views/subs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subs</h1>

<%= link_to 'New Sub', new_sub_path, class: 'btn btn-primary' %>

<%= @subs.each do |sub| %>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title"><%= link_to sub.title, sub_path(sub) %></h5>
            <%= link_to 'Edit', edit_sub_path(sub), class: 'card-link' %>
        </div>
    </div>
<% end %>

app/views/subs/new.html.erb
<%= render "form" %>

app/views/subs/show.html.erb
<p id="notice">
    <%= notice %>
</p>

<h1><%= @sub.title %></h1>


<%= @posts.each do |post| %>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title"><%= link_to post.title, post_path(post) %></h5>
            <p class="card-text"> <%= truncate(post.title, length: 60) %></p>
            <%= link_to 'Edit', edit_post_path(post), class: 'card-link' %>
            <button type="button" class="btn btn-success"><%= button_to 'Upvote', upvote_post_path(post), class: 'btn' %></button>
            <button type="button" class="btn btn-danger"><%= button_to 'Downvote', downvote_post_path(post), class: 'btn' %></button>

            <%= post.total %>
        </div>
    </div>
<% end %>

<%= @sub.attributes %>